name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies 
      run : apt-get install -y --no-install-recommends \
              capnproto \
              libcapnp-dev \
              libzmqpp-dev \
    - name: checks capnp sender
      run: cd message && g++ -Wall -I. -O2 -std=c++17 capnp_impl.cpp zmq_msg.h -lcapnp -lkj -lzmqpp -lzmq
    - name: make check
      run: make check
